//
//  main.cpp
//  LeetCode
//
//  Created by 郭妙友 on 17/2/5.
//  Copyright © 2017年 miaoyou.gmy. All rights reserved.
//

#include <iostream>
#include <vector>
#include <string>
#include <map>

#include <cmath>
#include <cstdio>
#include <cstdlib>

using namespace std;

/**
 
 389. Find the Difference Add to List
 
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 
 Example:
 
 Input:
 s = "abcd"
 t = "abcde"
 
 Output:
 e
 
 Explanation:
 'e' is the letter that was added.
 
 */


/**
 
 54 / 54 test cases passed.
 Status: Accepted
 Runtime: 16 ms
 
 */

int compare( const void *a, const void *b ){
    char *ch1 = (char *)a,*ch2 = (char *)b;
    
    return (*ch1) - (*ch2);
}


char findTheDifference(char* s, char* t) {
    int idx = (int)strlen(t)-1;
    qsort(s,strlen(s),sizeof(char),compare);
    qsort(t,strlen(t),sizeof(char),compare);
    for(int i=0;i<strlen(s);i++){
        if(s[i] != t[i]){
            idx = i;
            break;
        }
    }
    
    return t[idx];
}

int main(){
    return 0;
}
